support ce2ee validatioin

diff --git a/verify-prs b/verify-prs
--- a/verify-prs
+++ b/verify-prs
@@ -6,21 +6,18 @@ function warn () {
 
 function die () {
     local st
-    st=$?
+    st="$?"
     case $2 in
         (*[^0-9]*|'') : ;;
         (*) st=$2 ;;
     esac
-    warn "$1"
-    exit "$st"
-}
 
-function clean_up () {
-    local st
-    st=$?
-    warn "WARNING: $0 is terminated". "output dir $out_dir removed"
+    if [[ -n "$1" ]] ; then warn "$1" ; fi
+
+    warn "WARNING: $0 is terminated" "output dir $out_dir removed"
     rm -rf "$out_dir"
-    exit $st
+
+    exit "$st"
 }
 
 function show_help () {
@@ -29,24 +26,26 @@ function show_help () {
     cat <<-EOF
 Version: 0.1
  Author: Zachary Hu (zhucac AT outlook.com)
- Script: Compare between two revisions (e.g. release tags) and output commits, pull requests and pull requests without changelog.
-  Usage: ${prg} --org-repo kong/kong-ee --base-commit 3.4.3.2 --head-commit 3.4.3.3 [-v]
+ Script: Compare between two revisions (e.g. tags and branches) and output commits, PRs, PRs without changelog and PRs without CE2EE (experimental).
+  Usage: ${prg} --org-repo kong/kong-ee --base-commit 3.4.2.0 --head-commit 3.4.2.1 [-v]
 
-         ORG_REPO=kong/kong-ee BASE_COMMIT=3.4.3.2 HEAD_COMMIT=3.4.3.3 $prg
+         ORG_REPO=kong/kong-ee BASE_COMMIT=3.4.2.0 HEAD_COMMIT=3.4.2.1 $prg
 EOF
 }
 
 function set_globals () {
     ORG_REPO="${ORG_REPO:-kong/kong-ee}"
-    BASE_COMMIT="${BASE_COMMIT:-3.4.3.2}"
-    HEAD_COMMIT="${HEAD_COMMIT:-3.4.3.3}"
+    BASE_COMMIT="${BASE_COMMIT:-3.4.2.0}"
+    HEAD_COMMIT="${HEAD_COMMIT:-3.4.2.1}"
 
     verbose=0
-    out_dir=$(mktemp -dt output)
+    out_dir=$(mktemp -dt outputXXX)
     commits_file="${out_dir}/commits.txt"
     prs_file="${out_dir}/prs.txt"
-    prs_no_changelog_file="${out_dir}/no_changelog_prs.txt"
-    prs_no_cherrypick_file="${out_dir}/no_cherrypick_prs.txt"
+    prs_no_changelog_file="${out_dir}/prs_no_changelog.txt"
+    prs_no_cherrypick_label_file="${out_dir}/prs_no_cherrypick_label.txt"
+    prs_no_cross_reference_file="${out_dir}/prs_no_cross_reference.txt"
+    prs_no_ce2ee_file="${out_dir}/prs_no_ce2ee.txt"
 
     per_page=100
     num_of_pages=1
@@ -146,11 +145,18 @@ function prepare_args () {
 
 function get_num_pages_commits () {
     local paged_response
+
     paged_response=$( curl -i -sSL \
                            -H "Accept: application/vnd.github+json" \
                            -H "X-GitHub-Api-Version: 2022-11-28" \
                            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                            "https://api.github.com/repos/${ORG_REPO}/compare/${BASE_COMMIT}...${HEAD_COMMIT}?per_page=${per_page}" )
+
+    local status_line
+    status_line=$( sed -n 1p <<< "$paged_response" )
+    if ! [[ "$status_line" =~ 200 ]] ; then
+        die 'ERROR: cannot request GitHub API. Please check arguments or try option "-v"' 2
+    fi
 
     local link_header
     link_header=$( awk '/^link:/ { print; exit }' <<< "$paged_response" )
@@ -244,7 +250,7 @@ function check_changelog () {
     if type parallel >/dev/null 2>&1 ; then
         parallel check_pr_changelog '{}' <"$1"
     else
-        warn "WARNING: GNU parallel is not available, fallback to xargs"
+        warn "WARNING: GNU 'parallel' is not available, fallback to 'xargs'"
         <"$1" xargs -P "$bulk" -n1 -I'{}' bash -c 'check_pr_changelog "$@"' _ '{}'
     fi
     sort -uo "$prs_no_changelog_file" "$prs_no_changelog_file"
@@ -252,11 +258,11 @@ function check_changelog () {
     : ${in_fd}<&-
 }
 
-function check_pr_ce2ee () {
+function check_cherrypick_label () {
     if [[ -z "${1:+x}" ]] ; then return ; fi
 
     local label_pattern="cherry-pick kong-ee"
-    local req_url="https://api.github.com/repos/kong/kong/issues/PR_NUMBER/labels"
+    local req_url="https://api.github.com/repos/${ORG_REPO}/issues/PR_NUMBER/labels"
     local pr_number="${1##https://*/}"
     req_url="${req_url/PR_NUMBER/$pr_number}"
     mapfile -t < <( curl -sSL \
@@ -265,11 +271,29 @@ function check_pr_ce2ee () {
                          -H "X-GitHub-Api-Version: 2022-11-28" \
                          "$req_url" | jq -r '.[].name' )
 
-    local has_cherrypick=0
+    local has_label=0
     for l in "${MAPFILE[@]}" ; do
-        if [[ "$l" == ${label_pattern} ]] ; then has_cherrypick=1; break; fi
+        if [[ "$l" == ${label_pattern} ]] ; then has_label=1; break; fi
     done
-    if ! (( "$has_cherrypick" )) ; then echo "$1" | tee -a "$prs_no_cherrypick_file" ; fi
+    if ! (( "$has_label" )) ; then echo "$1" | tee -a "$prs_no_cherrypick_label_file" ; fi
+}
+
+function check_cross_reference () {
+    if [[ -z "${1:+x}" ]] ; then return ; fi
+
+    local req_url="https://api.github.com/repos/${ORG_REPO}/issues/PR_NUMBER/timeline"
+    local pr_number="${1##https://*/}"
+    req_url="${req_url/PR_NUMBER/$pr_number}"
+    local json_response
+    json_response=$( curl -sSL \
+                         -H "Accept: application/vnd.github+json" \
+                         -H "Authorization: Bearer ${GITHUB_TOKEN}" \
+                         -H "X-GitHub-Api-Version: 2022-11-28" \
+                         "$req_url" )
+
+    if ! jq -er '.[].source.issue | select((.pull_request != null) and (.pull_request.html_url | ascii_downcase | contains("kong/kong-ee")) and (.title | ascii_downcase | contains("cherry"))) | [.pull_request.html_url, .title] | @tsv' <<< "$json_response" >/dev/null ; then
+        echo "$1" | tee -a "$prs_no_cross_reference_file"
+    fi
 }
 
 function check_ce2ee () {
@@ -281,27 +305,40 @@ function check_ce2ee () {
         warn "WARNING: $1 not a valid file. Read from stdin -"
     fi
 
-    echo -e "\nPRs without cherry-pick label:"
     if [[ "$ORG_REPO" != "kong/kong" && "$ORG_REPO" != "Kong/kong" ]] ; then
-        warn "WARNING: skip cherry-pick on repo $ORG_REPO"
-        touch "$prs_no_cherrypick_file"
+        warn "WARNING: only check CE2EE for CE repo. Skip $ORG_REPO"
+        touch "$prs_no_cherrypick_label_file" "$prs_no_cross_reference_file"
         return
     fi
 
-    export ORG_REPO="$ORG_REPO" prs_no_cherrypick_file="$prs_no_cherrypick_file"
-    export -f check_pr_ce2ee
+    echo -e "\nPRs without 'cherry-pick kong-ee' label:"
+    export ORG_REPO="$ORG_REPO" prs_no_cherrypick_label_file="$prs_no_cherrypick_label_file"
+    export -f check_cherrypick_label
     if type parallel >/dev/null 2>&1 ; then
-        parallel check_pr_ce2ee '{}' <"$1"
+        parallel check_cherrypick_label '{}' <"$1"
     else
-        warn "WARNING: GNU parallel is not available, fallback to xargs"
-        <"$1" xargs -P "$bulk" -n1 -I'{}' bash -c 'check_pr_ce2ee "$@"' _ '{}'
+        warn "WARNING: GNU 'parallel' is not available, fallback to 'xargs'"
+        <"$1" xargs -P "$bulk" -n1 -I'{}' bash -c 'check_cherrypick_label "$@"' _ '{}'
     fi
-    sort -uo "$prs_no_cherrypick_file" "$prs_no_cherrypick_file"
+    sort -uo "$prs_no_cherrypick_label_file" "$prs_no_cherrypick_label_file"
+
+    echo -e "\nPRs without cross-referenced EE PRs with 'cherry' in the title:"
+    export ORG_REPO="$ORG_REPO" prs_no_cross_reference_file="$prs_no_cross_reference_file"
+    export -f check_cross_reference
+    if type parallel >/dev/null 2>&1 ; then
+        parallel check_cross_reference '{}' <"$1"
+    else
+        warn "WARNING: GNU 'parallel' is not available, fallback to 'xargs'"
+        <"$1" xargs -P "$bulk" -n1 -I'{}' bash -c 'check_cross_reference "$@"' _ '{}'
+    fi
+    sort -uo "$prs_no_cross_reference_file" "$prs_no_cross_reference_file"
+
+    comm -12 "$prs_no_cherrypick_label_file" "$prs_no_cross_reference_file" >> "$prs_no_ce2ee_file"
 }
 
 function main () {
     set -Eeo pipefail
-    trap clean_up SIGABRT SIGQUIT SIGHUP SIGINT
+    trap die ERR SIGABRT SIGQUIT SIGHUP SIGINT
 
     set_globals
     prepare_args "$@"
@@ -316,12 +353,14 @@ function main () {
 
     printf '%s\n' "" \
            "commits: $commits_file" \
-           "pull requests: $prs_file" \
-           "pull requests without changelog: $prs_no_changelog_file" \
-           "pull requests without cherry-pick: $prs_no_cherrypick_file" \
+           "PRs: $prs_file" \
+           "PRs without changelog: $prs_no_changelog_file" \
+           "CE PRs without 'cherry-pick kong-ee' label: $prs_no_cherrypick_label_file" \
+           "CE PRs without cross-referenced EE PRs with 'cherry' in the title: $prs_no_cross_reference_file" \
+           "CE PRs without CE2EE: $prs_no_ce2ee_file" \
            "" "Remeber to remove $out_dir"
 
-    trap "" EXIT
+    trap '' EXIT
 }
 
 if (( "$#" )) ; then main "$@" ; else show_help ; fi
